server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-discovery
eureka:
  intance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance}localhost:8761/eureka