server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msscustomer
          uri: lb://api-customer
          predicates:
            -Path=/customers/**
        - id: msswallet
          uri: lb://api-wallet
          predicates:
            -Path=/wallet/**

info:
  app:
    name: ${spring.application.name}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
